/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 qutub_scene.glb 
Author: Anushka (https://sketchfab.com/nerdysickness)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/qutb-minar-environment-block-out-239b025e19ea460eb87a0e66ac280d72
Title: Qutb Minar Environment Block-out
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import * as THREE from 'three'

export default function Model(props: GroupProps) {
    const { nodes, materials } = useGLTF('/qutub_scene.glb')
  
    return (
      <group {...props} dispose={null}>
        <group position={[-0.033, -0.007, 0.002]} rotation={[-0.027, 0.131, -0.003]} scale={0.001}>
          {nodes.node_id4_Material_78_0 instanceof THREE.Mesh && <mesh geometry={nodes.node_id4_Material_78_0.geometry} material={materials.Material_78} position={[0, 1.545, 179.271]} scale={[37.485, 190.049, 37.485]} />}
          {nodes.node_id6_Material_80_0 instanceof THREE.Mesh && <mesh geometry={nodes.node_id6_Material_80_0.geometry} material={materials.Material_80} position={[0, -190.124, 256]} scale={[512, 2.94, 512]} />}
          {nodes.node_id92_Material_82_0 instanceof THREE.Mesh && <mesh geometry={nodes.node_id92_Material_82_0.geometry} material={materials.Material_82} position={[1.03, 9.48, 191.654]} scale={0.276} />}
          {nodes.node_id102_Material_84_0 instanceof THREE.Mesh && <mesh geometry={nodes.node_id102_Material_84_0.geometry} material={materials.Material_84} position={[-14.646, -0.409, 196.551]} scale={[0.31, 0.262, 0.262]} />}
        </group>
      </group>
    )
  }
  
  useGLTF.preload('/qutub_scene.glb')
