/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/heartModel.glb -t -r public 
Author: E-learning UMCG (https://sketchfab.com/eLearningUMCG)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/cardiac-anatomy-external-view-e8e8c6685e82474d8393693fd0646dc7
Title: Cardiac Anatomy: external view
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MM634_BP51951_FMA4706_Coronary_sinus835_MM634_BP51951_FMA4706_Coronary_sinus835_0: THREE.Mesh
    MM634_BP51951_FMA4706_Coronary_sinus835_MM634_BP51951_FMA4706_Coronary_sinus835_0_1: THREE.Mesh
    MM634_BP51951_FMA4706_Coronary_sinus835_MM634_BP51951_FMA4706_Coronary_sinus835_0_2: THREE.Mesh
  }
  materials: {
    MM634_BP51951_FMA4706_Coronary_sinus835: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function HeartModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('../../src/assets/ThreeModels/heartModel.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={100}>
      <group position={[15.128, -227.508, 2.374]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.MM634_BP51951_FMA4706_Coronary_sinus835_MM634_BP51951_FMA4706_Coronary_sinus835_0.geometry} material={materials.MM634_BP51951_FMA4706_Coronary_sinus835} />
          <mesh geometry={nodes.MM634_BP51951_FMA4706_Coronary_sinus835_MM634_BP51951_FMA4706_Coronary_sinus835_0_1.geometry} material={materials.MM634_BP51951_FMA4706_Coronary_sinus835} />
          <mesh geometry={nodes.MM634_BP51951_FMA4706_Coronary_sinus835_MM634_BP51951_FMA4706_Coronary_sinus835_0_2.geometry} material={materials.MM634_BP51951_FMA4706_Coronary_sinus835} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../src/assets/ThreeModels/heartModel.glb');