/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/assets/inner_ear.glb -t -r 
Author: University of Dundee School of Medicine (https://sketchfab.com/tilt)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/anatomy-of-the-inner-ear-f80bda64666c4b8aaac8f63b7b82a0a0
Title: Anatomy of the Inner Ear
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
  }
  materials: {
    initialShadingGroup: THREE.MeshStandardMaterial
    lambert11SG: THREE.MeshStandardMaterial
    lambert12SG: THREE.MeshStandardMaterial
    lambert13SG: THREE.MeshStandardMaterial
    lambert5SG: THREE.MeshStandardMaterial
    lambert6SG: THREE.MeshStandardMaterial
    lambert8SG: THREE.MeshStandardMaterial
    lambert9SG: THREE.MeshStandardMaterial
    lambert10SG: THREE.MeshStandardMaterial
    lambert7SG: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function InnerEar(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/Models/InnerEar.glb') as GLTFResult
  const groupRef = useRef<THREE.Group>(null);

  useFrame(() => {
    if (groupRef.current) {
      // groupRef.current.rotation.x = Math.PI / 2;
      // groupRef.current.rotation.z = 3.2;
      groupRef.current.position.y = -3;
      // groupRef.current.position.z = 10;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert11SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert12SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert13SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert8SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lambert9SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.lambert10SG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/Models/InnerEar.glb')
