/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 D:/MERN/LDAI/3jsCrabnosis/public/assets/larynx.glb -t -r 
Author: University of Dundee School of Medicine (https://sketchfab.com/tilt)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/anatomy-of-the-larynx-a00bc73a303c46248db6a13a88b23404
Title: Anatomy of the Larynx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Thryoid_cartilage_Thyroid_Mat_0: THREE.Mesh
    Thyroepiglottic_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    R_Vestibular_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    Vocal_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    Right_Thyroid_Membrane_Vocal_Cords_Mat_0: THREE.Mesh
    Right_Thyroid_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    Median_Cricothyroid_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    L_Vestibular_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    Vical_Ligament01_Vocal_Cords_Mat_0: THREE.Mesh
    Left_Thyroid_Membrane_Vocal_Cords_Mat_0: THREE.Mesh
    Left_Thyroid_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    Hyoid_Hyoid_Mat_0: THREE.Mesh
    Hyoepiglottic_Ligament_Vocal_Cords_Mat_0: THREE.Mesh
    Epoglottis_Epiglottis_Mat_0: THREE.Mesh
    Cricoid_cartilage_Cricoid_0: THREE.Mesh
    Right_Arytenoid_cartilage_lambert8_0: THREE.Mesh
    Left_Arytenoid_cartilage_lambert8_0: THREE.Mesh
    Right_Corniculate_Cartilage_lambert8_0: THREE.Mesh
    Left_Corniculate_Cartilage_lambert8_0: THREE.Mesh
    Trachea_Vocal_Cords_Mat_0: THREE.Mesh
  }
  materials: {
    Thyroid_Mat: THREE.MeshStandardMaterial
    Vocal_Cords_Mat: THREE.MeshStandardMaterial
    Hyoid_Mat: THREE.MeshStandardMaterial
    Epiglottis_Mat: THREE.MeshStandardMaterial
    Cricoid: THREE.MeshStandardMaterial
    lambert8: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Larynx(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/Models/Larynx.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1356.104, -83.352]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Thryoid_cartilage_Thyroid_Mat_0.geometry} material={materials.Thyroid_Mat} />
        <mesh geometry={nodes.Thyroepiglottic_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.R_Vestibular_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Vocal_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Right_Thyroid_Membrane_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Right_Thyroid_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Median_Cricothyroid_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.L_Vestibular_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Vical_Ligament01_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Left_Thyroid_Membrane_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Left_Thyroid_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Hyoid_Hyoid_Mat_0.geometry} material={materials.Hyoid_Mat} />
        <mesh geometry={nodes.Hyoepiglottic_Ligament_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} />
        <mesh geometry={nodes.Epoglottis_Epiglottis_Mat_0.geometry} material={materials.Epiglottis_Mat} />
        <mesh geometry={nodes.Cricoid_cartilage_Cricoid_0.geometry} material={materials.Cricoid} />
        <mesh geometry={nodes.Right_Arytenoid_cartilage_lambert8_0.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.Left_Arytenoid_cartilage_lambert8_0.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.Right_Corniculate_Cartilage_lambert8_0.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.Left_Corniculate_Cartilage_lambert8_0.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.Trachea_Vocal_Cords_Mat_0.geometry} material={materials.Vocal_Cords_Mat} position={[0, -83.352, 1279.854]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/Models/Larynx.glb')
